version: "3.1"
services:

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    volumes:
      - /data/pizarra/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pizarra
      - POSTGRES_PASSWORD=pizarra
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  pizarra-web:
    image: pizarra
    volumes:
      - ./app/uploads:/opt/pizarra/app/uploads
    ports:
      - 5000:5000
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
      - CONFIG_MODE=Production

  pizarra-woker:
    image: pizarra
    volumes:
      - ./app/uploads:/opt/pizarra/app/uploads
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
      - CONFIG_MODE=Production
      - APP_MODE=Worker

# run
# docker-compose up -d --scale pizarra-woker=2