version: "3.7"
services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    volumes:
      - /data/pizarra/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=pizarra
      - POSTGRES_PASSWORD=pizarra
    restart: unless-stopped
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  pizarra-woker:
    image: pizarra
    deploy:
      resources:
        limits:
          cpus: '3'
      mode: replicated
      replicas: 2
    volumes:
      - ./app/uploads:/opt/pizarra/app/uploads
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379/0
      - CONFIG_MODE=Production

# run
# docker-compose up -d --scale pizarra-woker=2