apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    tier: backend
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: backend
  template:
    metadata:
      labels:
        app: postgres
        tier: backend
    spec:
      containers:
        - image: postgres:9.6-alpine
          name: postgres
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pizarra-credentials
                key: db_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pizarra-credentials
                key: db_password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: nfs-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: nfs-volume
          nfs:
            server: nfs-server.default.svc.cluster.local
            path: "/"
            readOnly: false